"""Regression-corpus validation for the M2 envelope.

Every slug in ``REGRESSION_SLUGS`` is pinned as a byte-diff regression case:
running ``companyctx fetch <site> --mock`` must reproduce the committed
``fixtures/<slug>/expected.json`` once ``fetched_at`` is scrubbed. The set
splits into three groups:

- Five synthetic-corpus fixtures spanning all five detectable stacks
  (WordPress, Squarespace, Wix, Webflow, custom/no-marker) across three
  niches — a regression in the extractor, tech-stack detector, or envelope
  serializer trips at least one of them.
- Two FM-7 failure-shape fixtures (`fm7-js-redirect-root`,
  `fm7-maintenance-page`) promoted from the 2026-04-21 durability run — they
  guard the thin/empty `homepage_text` envelope shape.
- One FM-13 network-failure fixture (`fm13-timeout-smb-01`) driven by the
  `fixture-block.txt` sentinel (see issue #40) — it locks the degraded
  envelope shape for network-level failures that produce no HTML.

This is intentionally a regression snapshot, not a real golden oracle. Real
golden validation against the external brief pipeline's output is a separate
v0.1.0 release gate because those expected outputs must come from an external
source, not from `companyctx.core.run()` itself.

The remaining 25 synthetic fixtures still have committed ``expected.json``
files generated by the same orchestrator; they're exercised looser by
``tests/test_fixtures_corpus.py``.

Rationale for each subset's picking lives in ``fixtures/README.md`` under
"Regression corpus".
"""

from __future__ import annotations

import re
from pathlib import Path

import pytest
from typer.testing import CliRunner

from companyctx.cli import app

FIXTURES_DIR = Path(__file__).resolve().parent.parent / "fixtures"
FETCHED_AT_RE = re.compile(rb'"fetched_at":\s*"[^"]+"')

REGRESSION_SLUGS = (
    "acme-bakery",
    "coastal-fitness",
    "midtown-auto",
    "mapleridge-contractor",
    "oakleaf-bakery",
    # FM-7 failure-shape regressions promoted from the 2026-04-21 durability
    # run — see fixtures/durability-report-2026-04-21.md. Both emit status=ok
    # with thin/empty homepage_text (the "brochureware / maintenance / JS-
    # redirect" shape per docs/RISK-REGISTER.md §FM-7). Fixtures guard
    # against an extractor change that silently starts hallucinating
    # content from an effectively empty page.
    "fm7-js-redirect-root",
    "fm7-maintenance-page",
    # COX-44 empty-response honesty regression. With the v0.3 provider
    # gate, an HTTP 200 that extracts to < EMPTY_RESPONSE_BYTES flips from
    # the v0.2 silent-success shape (status: ok, homepage_text: "") to the
    # honest shape: status: degraded, error.code: "empty_response" with an
    # actionable suggestion. The fm7-* fixtures above also exercise this
    # code path post-COX-44; this dedicated fixture is the minimal,
    # zero-content trigger so the pin survives a future fm7-* semantic
    # rename. See docs/SPEC.md §empty_response.
    "empty-response",
    # COX-52 FM-7 thin-body regressions — 19 pseudonymized seeds from
    # the v0.2 partner-integration validation (`research/2026-04-22-v0.2-
    # joel-integration-validation.md` §3). Each extracts to 64-1023
    # UTF-8 bytes: cleared the v0.3.0 64-byte floor (silent-success) and
    # now trips the v0.4.0 1024-byte floor. Pinned as byte-diff fixtures
    # so the envelope shape they produce is frozen — any regression in
    # the empty-response classifier or the thin-body gate breaks the
    # byte-diff here before it reaches a partner release.
    "fm7-thin-bariatric-01",
    "fm7-thin-botox-01",
    "fm7-thin-chiropractic-01",
    "fm7-thin-dentistry-01",
    "fm7-thin-dermatology-01",
    "fm7-thin-gutters-01",
    "fm7-thin-gutters-02",
    "fm7-thin-inspection-01",
    "fm7-thin-medspa-01",
    "fm7-thin-orthodontics-01",
    "fm7-thin-plastic-surgery-01",
    "fm7-thin-re-photography-01",
    "fm7-thin-re-photography-02",
    "fm7-thin-re-staging-01",
    "fm7-thin-re-staging-02",
    "fm7-thin-virtual-staging-01",
    "fm7-thin-virtual-staging-02",
    "fm7-thin-waste-01",
    "fm7-thin-window-door-01",
    # FM-13 network-failure regression. Driven by the fixture-block.txt
    # sentinel honoured by site_text_trafilatura._from_fixture: the file's
    # contents become the BlockedError reason verbatim, the provider maps
    # that to status=failed, and the orchestrator aggregates a single
    # failed provider to status=degraded. Locks the envelope shape that
    # downstream pipelines branch on for FM-13 timeouts (see issue #40).
    "fm13-timeout-smb-01",
    # COX-43 / #78 tech-fingerprint false-positive regression. HTML
    # mentions WordPress / Shopify / Squarespace / Wix / Webflow / Elementor
    # in prose, comments, and third-party widget src URLs but loads none of
    # them. The v0.2 substring detector emitted all six; the v0.3 detector
    # restricts to high-confidence signals (generator meta, framework-owned
    # asset hostnames, platform class/data attrs on html/body) and pins
    # tech_stack=[]. Byte-diff regression gate against a reversion.
    "tech-fp-mentions-only",
)


def _scrub_fetched_at(raw: bytes) -> bytes:
    return FETCHED_AT_RE.sub(b'"fetched_at": "<scrubbed>"', raw)


@pytest.mark.parametrize("slug", REGRESSION_SLUGS)
def test_regression_fixture_matches_expected_envelope_bytes(slug: str) -> None:
    expected_path = FIXTURES_DIR / slug / "expected.json"
    expected = _scrub_fetched_at(expected_path.read_bytes())

    runner = CliRunner()
    result = runner.invoke(
        app,
        [
            "fetch",
            f"{slug}.example",
            "--mock",
            "--json",
            "--fixtures-dir",
            str(FIXTURES_DIR),
        ],
    )
    assert result.exit_code == 0, result.stdout
    assert _scrub_fetched_at(result.stdout.encode("utf-8")) == expected, slug
