"""Real golden corpus — 5 hand-curated oracles from external brief artifacts.

Closes the gap flagged as HIGH by the Codex review on PR #19 and tracked in
issue #24. Five fixtures are marked ``.hand-curated``: their
``expected.json`` is a **frozen oracle** representing raw observations
captured by the external B2B brief pipeline against the same underlying
sites. The oracle is not regenerated by :func:`companyctx.core.run`.

Running ``companyctx fetch <slug>.example --mock --json`` against the
sanitized HTML / provider-JSON fixtures must produce bytes matching the
oracle, modulo ``fetched_at``. A drift here signals that the extractor,
tech-stack detector, or envelope serializer no longer agrees with what the
external pipeline captured for the same input.

Distinct from ``tests/test_regression_corpus.py``:

- Regression corpus: synthetic inputs with oracles rendered by ``core.run``
  (circular by construction — guards against byte-level drift only).
- Real golden corpus (this file): inputs sanitized from real external brief
  artifacts; oracles hand-curated from the brief's observations (breaks the
  circle — guards against extraction drift from an external ground truth).

The five slugs and the brief artifacts they derive from are listed in
``fixtures/<slug>/SOURCE.md``.
"""

from __future__ import annotations

import importlib.util
import re
import sys
from pathlib import Path

import pytest
from typer.testing import CliRunner

from companyctx.cli import app

FIXTURES_DIR = Path(__file__).resolve().parent.parent / "fixtures"
FETCHED_AT_RE = re.compile(rb'"fetched_at":\s*"[^"]+"')

REAL_GOLDEN_SLUGS = (
    "northarlington-pharmacy-01",
    "cary-hormone-02",
    "hinsdale-derm-03",
    "birmingham-iv-04",
    "charleston-medspa-05",
)


def _scrub_fetched_at(raw: bytes) -> bytes:
    return FETCHED_AT_RE.sub(b'"fetched_at": "<scrubbed>"', raw)


@pytest.mark.parametrize("slug", REAL_GOLDEN_SLUGS)
def test_real_golden_fixture_matches_hand_curated_oracle(slug: str) -> None:
    fixture_dir = FIXTURES_DIR / slug
    assert (fixture_dir / ".hand-curated").exists(), (
        f"{fixture_dir}/.hand-curated is missing — real-golden fixtures must "
        "carry the marker so scripts/build-fixtures.py refuses to regenerate them"
    )
    assert (fixture_dir / "SOURCE.md").exists(), (
        f"{fixture_dir}/SOURCE.md is missing — every real-golden fixture must "
        "cite the external brief artifact it was sanitized from"
    )

    expected = _scrub_fetched_at((fixture_dir / "expected.json").read_bytes())

    runner = CliRunner()
    result = runner.invoke(
        app,
        [
            "fetch",
            f"{slug}.example",
            "--mock",
            "--json",
            "--fixtures-dir",
            str(FIXTURES_DIR),
        ],
    )
    assert result.exit_code == 0, result.stdout
    assert _scrub_fetched_at(result.stdout.encode("utf-8")) == expected, slug


def _load_build_fixtures_module() -> object:
    """Import ``scripts/build-fixtures.py`` dynamically.

    The file is named with a hyphen, so the normal ``import`` machinery
    does not find it; we load it via ``importlib.util`` instead. Caching
    on ``sys.modules`` keeps later calls cheap.
    """
    mod_name = "scripts_build_fixtures"
    if mod_name in sys.modules:
        return sys.modules[mod_name]
    script_path = Path(__file__).resolve().parent.parent / "scripts" / "build-fixtures.py"
    spec = importlib.util.spec_from_file_location(mod_name, script_path)
    assert spec is not None and spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    sys.modules[mod_name] = module
    spec.loader.exec_module(module)
    return module


def test_build_fixtures_refuses_to_overwrite_hand_curated(tmp_path: Path) -> None:
    """Guard invariant: any fixture with a ``.hand-curated`` marker must not
    be regenerated by ``scripts/build-fixtures.py``, regardless of mode."""
    module = _load_build_fixtures_module()

    synthetic_prospects = module.build_synthetic_prospects()  # type: ignore[attr-defined]
    target = synthetic_prospects[0]

    site_dir = tmp_path / target.slug
    site_dir.mkdir()
    marker = site_dir / module.HAND_CURATED_MARKER  # type: ignore[attr-defined]
    marker.write_text("hand-curated — do not regenerate\n", encoding="utf-8")

    with pytest.raises(module.HandCuratedFixtureError) as excinfo:  # type: ignore[attr-defined]
        module.write_prospect(target, tmp_path)  # type: ignore[attr-defined]
    assert target.slug in str(excinfo.value)
    # Marker survives; no other files are materialized.
    assert marker.exists()
    assert not (site_dir / "homepage.html").exists()


def test_every_real_golden_fixture_carries_the_marker() -> None:
    """Sanity: the marker is the only thing that prevents regeneration."""
    for slug in REAL_GOLDEN_SLUGS:
        marker = FIXTURES_DIR / slug / ".hand-curated"
        assert marker.exists(), f"{slug} is missing the .hand-curated marker"
