"""Regression-corpus validation for the M2 envelope.

Five fixtures are pinned as regression cases: for each, running
``companyctx fetch <site> --mock`` must produce bytes matching the committed
``fixtures/<slug>/expected.json`` once ``fetched_at`` is scrubbed.

This is intentionally a regression snapshot, not a real golden oracle. Real
golden validation against Joel's D100 brief artifacts is a separate v0.1.0
release gate because those expected outputs must come from an external source,
not from `companyctx.core.run()` itself.

These five span all five detectable stacks (WordPress, Squarespace, Wix,
Webflow, custom/no-marker) and three niches, so a regression in the
extractor, tech-stack detector, or envelope serializer trips at least one
case. The remaining 25 fixtures still have committed ``expected.json`` files
generated by the same orchestrator; they're exercised looser by
``tests/test_fixtures_corpus.py``.

Rationale for the five-pick narrowing lives in ``fixtures/README.md`` under
"Regression corpus".
"""

from __future__ import annotations

import re
from pathlib import Path

import pytest
from typer.testing import CliRunner

from companyctx.cli import app

FIXTURES_DIR = Path(__file__).resolve().parent.parent / "fixtures"
FETCHED_AT_RE = re.compile(rb'"fetched_at":\s*"[^"]+"')

REGRESSION_SLUGS = (
    "acme-bakery",
    "coastal-fitness",
    "midtown-auto",
    "mapleridge-contractor",
    "oakleaf-bakery",
    # FM-7 failure-shape regressions promoted from the 2026-04-21 durability
    # run — see fixtures/durability-report-2026-04-21.md. Both emit status=ok
    # with thin/empty homepage_text (the "brochureware / maintenance / JS-
    # redirect" shape per docs/RISK-REGISTER.md §FM-7). Fixtures guard
    # against an extractor change that silently starts hallucinating
    # content from an effectively empty page.
    "fm7-js-redirect-root",
    "fm7-maintenance-page",
)


def _scrub_fetched_at(raw: bytes) -> bytes:
    return FETCHED_AT_RE.sub(b'"fetched_at": "<scrubbed>"', raw)


@pytest.mark.parametrize("slug", REGRESSION_SLUGS)
def test_regression_fixture_matches_expected_envelope_bytes(slug: str) -> None:
    expected_path = FIXTURES_DIR / slug / "expected.json"
    expected = _scrub_fetched_at(expected_path.read_bytes())

    runner = CliRunner()
    result = runner.invoke(
        app,
        [
            "fetch",
            f"{slug}.example",
            "--mock",
            "--json",
            "--fixtures-dir",
            str(FIXTURES_DIR),
        ],
    )
    assert result.exit_code == 0, result.stdout
    assert _scrub_fetched_at(result.stdout.encode("utf-8")) == expected, slug
