"""Golden-corpus validation for the M2 envelope.

Five fixtures are marked *golden*: for each, running
``companyctx fetch <site> --mock`` must produce an envelope byte-identical to
the committed ``fixtures/<slug>/expected.json`` (modulo ``fetched_at``).

These five span all five detectable stacks (WordPress, Squarespace, Wix,
Webflow, custom/no-marker) and three niches, so a regression in the
extractor, tech-stack detector, or envelope serializer trips at least one
case. The remaining 25 fixtures still have committed ``expected.json`` files
generated by the same orchestrator; they're exercised looser by
``tests/test_fixtures_corpus.py``.

Rationale for the five-pick narrowing lives in ``fixtures/README.md`` under
"Golden corpus".
"""

from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path

import pytest

from companyctx import core

FIXTURES_DIR = Path(__file__).resolve().parent.parent / "fixtures"
PINNED_FETCHED_AT = datetime(2026, 4, 20, tzinfo=timezone.utc)

GOLDEN_SLUGS = (
    "acme-bakery",
    "coastal-fitness",
    "midtown-auto",
    "mapleridge-contractor",
    "oakleaf-bakery",
)


def _strip_fetched_at(envelope: dict[str, object]) -> dict[str, object]:
    data = envelope.get("data")
    if isinstance(data, dict):
        data.pop("fetched_at", None)
    return envelope


@pytest.mark.parametrize("slug", GOLDEN_SLUGS)
def test_golden_fixture_matches_expected_envelope(slug: str) -> None:
    expected_path = FIXTURES_DIR / slug / "expected.json"
    expected = json.loads(expected_path.read_text(encoding="utf-8"))

    env = core.run(
        f"{slug}.example",
        mock=True,
        fixtures_dir=FIXTURES_DIR,
        fetched_at=PINNED_FETCHED_AT,
    )
    actual = env.model_dump(mode="json")

    assert _strip_fetched_at(actual) == _strip_fetched_at(expected), slug
